# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.network "forwarded_port", guest: 8081, host: 8081

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    #vb.memory = "4096"
    vb.cpus = "2"
    vb.gui = true
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y epel-release
    sudo yum install -y vim git deltarpm htop ncdu tree
    sudo yum update -y
  SHELL
end
