# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define 'windows' do |win|
    win.vm.box = 'opentable/win-2012r2-standard-amd64-nocm'

    win.vm.provider 'virtualbox' do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.gui = true
    end
  end

  config.vm.define 'client' do |l|
    l.vm.box = 'centos/7'
    l.vm.provider 'virtualbox' do |vb|
      vb.memory = 512
      vb.cpus = 2
    end

    config.vm.provision 'shell', inline: <<-SHELL
      yum install -y vim openscap scap-security-guide realmd
    SHELL
  end
end
