# Config for sworkstyle
#
# You can rename workspaces based on the exact application names or by generic pattern.
# When it could not match anything it will use the fallback.
#
# format:
#
#   "{pattern}" = { type = "generic" | "exact", value = "{icon}" }
#
# pattern: can either be the exact app_name or a piece of text contained in the title ignoring casing.
# icon: Your beatifull icon
#
# You can also you the shorthand for exact matching using
#   "{pattern}" = "{icon}"
#
# If it couldn't match something it will print:
#
# WARN [sworkstyle:config] No match for "{app_name}" with title "{title}"
#
# You can use {title} to do a generic matching
# You can use {app_name} to do a exact match

fallback = ''

[matching]
'discord' = ''
'balena-etcher' = ''
'Chia Blockchain' = ''
'Steam' = ''
'vlc' = ''
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Postman' = ''
'Insomnia' = ''
'Bitwarden' = ''
'Google-chrome' = ''
'Chromium' = ''
'Slack' = ''
'Code' = ''
'code-oss' = ''
'jetbrains-studio' = ''
'Spotify' = ''
'GitHub Desktop' = ''
'/(?i)Github.*Firefox/' = ''
'firefox' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/nvim ?\w*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'Alacritty' = ''
"gnome-terminal-server" = ""
"kgx" = ""
