if ENV['NODES'].to_i > 0 && ENV['NODES']
  $nodes_count = ENV['NODES'].to_i
end

$nodes_count = 3

Vagrant.configure('2') do |config|
  config.vm.box = 'centos/7'
  config.ssh.forward_agent = true
  config.vm.network 'public_network', bridge: 'wlp58s0'
  config.vm.provision :hosts, :sync_hosts => true

  (1..$nodes_count).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}.thebes.jeef.me"
    end
  end
end

