# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "fedora/29-cloud-base"

  # config.vm.network "forwarded_port", guest: 8081, host: 8081

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    #vb.memory = "4096"
    vb.cpus = "2"
  end

  #config.vm.provision "shell", inline: <<-SHELL
  #  sudo rpm -ivh http://yum.puppetlabs.com/puppet/puppet5-release-el-7.noarch.rpm
  #  sudo yum install -y puppet-agent epel-release
  #  sudo yum install -y vim git deltarpm htop ncdu tree
  #SHELL
end
